infinivert_git_hub_commit_history_test:
    organization: "waybetterdev"
    # Username and Password are optional but recommended. See https://developer.github.com/v3/#rate-limiting
    username: ""
    password: ""